#-- copyright
# OpenProject is an open source project management software.
# Copyright (C) the OpenProject GmbH
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License version 3.
#
# OpenProject is a fork of ChiliProject, which is a fork of Redmine. The copyright follows:
# Copyright (C) 2006-2013 Jean-Philippe Lang
# Copyright (C) 2010-2013 the ChiliProject Team
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
#
# See COPYRIGHT and LICENSE files for more details.
#++

class CreateHierarchicalItems < ActiveRecord::Migration[7.1]
  def change
    create_table :hierarchical_items do |t|
      t.integer :parent_id
      t.integer :sort_order
      t.string :label
      t.string :short
      t.boolean :is_deleted, default: false, null: false

      t.timestamps
    end

    add_reference "hierarchical_items", :custom_field, foreign_key: true

    # auto-generated by closure_tree
    create_table :hierarchical_item_hierarchies, id: false do |t|
      t.integer :ancestor_id, null: false
      t.integer :descendant_id, null: false
      t.integer :generations, null: false
    end

    add_index :hierarchical_item_hierarchies, %i[ancestor_id descendant_id generations],
              unique: true,
              name: "item_anc_desc_idx"

    add_index :hierarchical_item_hierarchies, [:descendant_id],
              name: "item_desc_idx"
  end
end
